meta_title: "Les Services de Benoit"
meta_description: "Aide à la personne, prestations à domicile sur mesure. Bénéficier de 50% de remise grace aux services à la personne."
meta_image: "servicesdebenoit.png" # Une image dans votre dossier app/assets/images/

